---
title: "Exploratory analysis for COVID paper"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r}
# Attach packages
library(tidyverse)
library(car)
library(RcmdrMisc)

# Read in data
source('~/Documents/IWDA Consultancy 2/data/Dimension construction/Sols_dimensions.R')
setwd("~/Documents/IWDA Consultancy 2/Report chapters")
source('summaryfuncs.R')
setwd("~/Documents/IWDA Consultancy 2/Thematic papers")

data$Age_bracket_ind <- cut(data$Age_ind, breaks = c(0, 18, 24, 34, 44, 54, 64, 74, 84, 150),
                            ordered_result = TRUE, labels = c('<18', '18-24', '25-34', '35-44', 
                                                              '45-54', '55-64', '65-74', '75-84', 
                                                              '85+'))

data$Province_ind <- car::recode(data$Province_ind, "1 = 'Central'; 2 = 'Guadalcanal'")
```

```{r, include = FALSE}
deprive <- function (raw_score){
  raw_score <- raw_score * 4
  cats_score <- ordered(cut(raw_score ,breaks=c(0,1.001,2.001,3.001,4.001),
           labels=factor(c("Most deprived","Deprived","Somewhat deprived","Least deprived")),right = FALSE))
  return(cats_score)}


# Initialise easy summary function

summarise_dim_score <- function (score, df = data, factorise = TRUE, by_province = FALSE) {
  if (factorise) {
    df$fact_score <- deprive(pull(data[score]))
  } else {
    df$fact_Score <- pull(data[score])
  }
  
  if (!by_province) {
    df %>%
    select(fact_score, Gender_ind) %>%
    filter(Gender_ind =='Male' | Gender_ind == 'Female') %>%
    na.omit() %>%
    group_by(fact_score, Gender_ind) %>%
    count() %>%
    group_by(Gender_ind) %>%
    mutate(prop = prop.table(n)) %>%
    ggplot(aes(x = fact_score, y = prop, fill = Gender_ind)) +
      geom_col(position = 'dodge') +
      scale_x_discrete(limits = rev(levels(data$fact_score))) +
      geom_text(size = 3, position = position_dodge(width = 1), aes(label = scales::percent(prop, 2), vjust = -1))
  } else if (by_province) {
  df %>%
    select(fact_score, Gender_ind, Province_ind) %>%
    filter(Gender_ind =='Male' | Gender_ind == 'Female') %>%
    na.omit() %>%
    group_by(fact_score, Gender_ind, Province_ind) %>%
    count() %>%
    group_by(Gender_ind, Province_ind) %>%
    mutate(prop = prop.table(n)) %>%
    ggplot(aes(x = fact_score, y = prop, fill = Gender_ind)) +
      geom_col(position = 'dodge') +
      scale_x_discrete(limits = rev(levels(data$fact_score))) +
      geom_text(size = 3, position = position_dodge(width = 1), aes(label = scales::percent(prop, 2), vjust = -1)) +
      facet_grid(cols = vars(Province_ind))
}
  }
```  


```{r}
# Initialise item score summary
summarise_item <- function(x, recode_string, by_province = FALSE) {
  if(class(recode_string) == "character") {
    data$x_recode <- car::recode(pull(data[,x]), recode_string)
  } else {
    data$x_recode <- pull(data[,x])
  }
  
  if(!by_province) {
    data %>%
    select(x_recode, Gender_ind) %>%
    filter(Gender_ind =='Male' | Gender_ind == 'Female') %>%
    na.omit() %>%
    group_by(x_recode, Gender_ind) %>%
    count() %>%
    group_by(Gender_ind) %>%
    mutate(prop = prop.table(n)) %>%
    ggplot(aes(x = x_recode, y = prop, fill = Gender_ind)) +
      geom_col(position = 'dodge') +
      geom_text(size = 3, position = position_dodge(width = 1), aes(label = scales::percent(prop, 2), vjust = -1))
  } else if (by_province) {
    data %>%
    select(x_recode, Gender_ind, Province_ind) %>%
    filter(Gender_ind =='Male' | Gender_ind == 'Female') %>%
    na.omit() %>%
    group_by(x_recode, Gender_ind, Province_ind) %>%
    count() %>%
    group_by(Gender_ind, Province_ind) %>%
    mutate(prop = prop.table(n)) %>%
    ggplot(aes(x = x_recode, y = prop, fill = Gender_ind)) +
      geom_col(position = 'dodge') +
      geom_text(size = 3, position = position_dodge(width = 1), aes(label = scales::percent(prop, 2), vjust = -1)) +
      facet_wrap(vars(Province_ind))
  }
}

```


## Additional analysis ##

**School attainment**

```{r, include = FALSE}
data$Education_level_completion.highest_recode <- factor(data$Education_level_completion.highest, ordered = FALSE, labels = c('No schooling', 'Some primary', 'Primary', 'Some secondary/high school', 'Secondary/high school', 'Some tertiary: Vocational/ technical', 'Some tertiary: university', 'Tertiary: Vocational/technical', 'Tertiary: university', 'Refused to answer'))

data %>%
  select(Education_level_completion.highest_recode, Gender_ind, Age_bracket_ind) %>%
      filter(Gender_ind == 'Male' | Gender_ind == 'Female') %>%
      group_by(Education_level_completion.highest_recode, Gender_ind, Age_bracket_ind) %>%
      count() %>%
      group_by(Gender_ind, Age_bracket_ind) %>%
      mutate(prop = prop.table(n))%>%
      ggplot(aes(x = Age_bracket_ind, y = prop, fill = Education_level_completion.highest_recode)) +
      geom_col(position = 'stack') +
      geom_text(size = 3, position = position_stack(), aes(label = scales::percent(prop, 2), vjust = 1)) +
        facet_grid(rows = vars(Gender_ind))
```

```{r}
colPercents(xtabs(~data$Education_level_completion.highest_recode + data$Gender_ind))
```

```{r}
men <- data %>% filter(Gender_ind == 'Male')
women <- data %>% filter(Gender_ind == 'Female')
colPercents(xtabs(~men$Education_level_completion.highest_recode + men$Age_bracket_ind))
colPercents(xtabs(~women$Education_level_completion.highest_recode + women$Age_bracket_ind))

```

```{r}
colPercents(xtabs(~data$Education_level_completion.highest_recode + data$Province_ind))
```

#### Crowding ####

```{r}
data$Shelter_habitability_crowded.too_crowded_recode <- car::recode(data$Shelter_habitability_crowded.too_crowded, "1 = 'Yes'; 2 = 'No'; else = NA")

colPercents(xtabs(~data$Shelter_habitability_crowded.too_crowded_recode + data$Gender_ind))
```

```{r}
colPercents(xtabs(~data$Shelter_habitability_crowded.too_crowded_recode + data$Gender_ind + data$Province_ind))
```

